/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddBankDTO,
  BankSchema,
  HTTPValidationError,
  OkResponseSchema,
} from '../models/index';
import {
    AddBankDTOFromJSON,
    AddBankDTOToJSON,
    BankSchemaFromJSON,
    BankSchemaToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    OkResponseSchemaFromJSON,
    OkResponseSchemaToJSON,
} from '../models/index';

export interface AddBankApiV1BanksPostRequest {
    addBankDTO: AddBankDTO;
}

export interface ConnectUserBankApiV1BanksBankIdAddConsentPostRequest {
    bankId: number;
}

export interface RejectConsentApiV1BanksBankIdRejectConsentPostRequest {
    bankId: number;
}

/**
 * 
 */
export class BankApi extends runtime.BaseAPI {

    /**
     * Add Bank
     */
    async addBankApiV1BanksPostRaw(requestParameters: AddBankApiV1BanksPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BankSchema>> {
        if (requestParameters['addBankDTO'] == null) {
            throw new runtime.RequiredError(
                'addBankDTO',
                'Required parameter "addBankDTO" was null or undefined when calling addBankApiV1BanksPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/banks/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddBankDTOToJSON(requestParameters['addBankDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BankSchemaFromJSON(jsonValue));
    }

    /**
     * Add Bank
     */
    async addBankApiV1BanksPost(requestParameters: AddBankApiV1BanksPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BankSchema> {
        const response = await this.addBankApiV1BanksPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Connect User Bank
     */
    async connectUserBankApiV1BanksBankIdAddConsentPostRaw(requestParameters: ConnectUserBankApiV1BanksBankIdAddConsentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OkResponseSchema>> {
        if (requestParameters['bankId'] == null) {
            throw new runtime.RequiredError(
                'bankId',
                'Required parameter "bankId" was null or undefined when calling connectUserBankApiV1BanksBankIdAddConsentPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/banks/{bankId}/add-consent/`;
        urlPath = urlPath.replace(`{${"bankId"}}`, encodeURIComponent(String(requestParameters['bankId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkResponseSchemaFromJSON(jsonValue));
    }

    /**
     * Connect User Bank
     */
    async connectUserBankApiV1BanksBankIdAddConsentPost(requestParameters: ConnectUserBankApiV1BanksBankIdAddConsentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OkResponseSchema> {
        const response = await this.connectUserBankApiV1BanksBankIdAddConsentPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Banks
     */
    async getBanksApiV1BanksGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BankSchema>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/banks/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BankSchemaFromJSON));
    }

    /**
     * Get Banks
     */
    async getBanksApiV1BanksGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BankSchema>> {
        const response = await this.getBanksApiV1BanksGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Reject Consent
     */
    async rejectConsentApiV1BanksBankIdRejectConsentPostRaw(requestParameters: RejectConsentApiV1BanksBankIdRejectConsentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OkResponseSchema>> {
        if (requestParameters['bankId'] == null) {
            throw new runtime.RequiredError(
                'bankId',
                'Required parameter "bankId" was null or undefined when calling rejectConsentApiV1BanksBankIdRejectConsentPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/banks/{bankId}/reject-consent/`;
        urlPath = urlPath.replace(`{${"bankId"}}`, encodeURIComponent(String(requestParameters['bankId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkResponseSchemaFromJSON(jsonValue));
    }

    /**
     * Reject Consent
     */
    async rejectConsentApiV1BanksBankIdRejectConsentPost(requestParameters: RejectConsentApiV1BanksBankIdRejectConsentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OkResponseSchema> {
        const response = await this.rejectConsentApiV1BanksBankIdRejectConsentPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
