/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  ProductRecommendation,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ProductRecommendationFromJSON,
    ProductRecommendationToJSON,
} from '../models/index';

export interface RecommendStubApiV1RecommendClientIdPostRequest {
    clientId: string;
    topN?: number;
    useMl?: boolean;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Recommend Stub
     */
    async recommendStubApiV1RecommendClientIdPostRaw(requestParameters: RecommendStubApiV1RecommendClientIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProductRecommendation>>> {
        if (requestParameters['clientId'] == null) {
            throw new runtime.RequiredError(
                'clientId',
                'Required parameter "clientId" was null or undefined when calling recommendStubApiV1RecommendClientIdPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['topN'] != null) {
            queryParameters['top_n'] = requestParameters['topN'];
        }

        if (requestParameters['useMl'] != null) {
            queryParameters['use_ml'] = requestParameters['useMl'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/recommend/{client_id}`;
        urlPath = urlPath.replace(`{${"client_id"}}`, encodeURIComponent(String(requestParameters['clientId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProductRecommendationFromJSON));
    }

    /**
     * Recommend Stub
     */
    async recommendStubApiV1RecommendClientIdPost(requestParameters: RecommendStubApiV1RecommendClientIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProductRecommendation>> {
        const response = await this.recommendStubApiV1RecommendClientIdPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
