"""banks table, user fields

Revision ID: 3d560f1fb1fd
Revises: 087964d90237
Create Date: 2025-11-06 09:40:05.542712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d560f1fb1fd'
down_revision: Union[str, Sequence[str], None] = '087964d90237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('api_url', sa.String(length=32), nullable=True),
    sa.Column('client_id', sa.String(length=32), nullable=True),
    sa.Column('client_secret', sa.String(length=264), nullable=True),
    sa.Column('access_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_url'),
    sa.UniqueConstraint('name')
    )
    op.add_column('users_user', sa.Column(
        'consents', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_user', 'consents')
    op.drop_table('banks_bank')
    # ### end Alembic commands ###
