"""upd colums

Revision ID: 5329eb95b6ca
Revises: 3d560f1fb1fd
Create Date: 2025-11-07 14:55:26.223745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5329eb95b6ca'
down_revision: Union[str, Sequence[str], None] = '3d560f1fb1fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_user', sa.Column('updated_accounts', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users_user', sa.Column('updated_transactions', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_user', 'updated_transactions')
    op.drop_column('users_user', 'updated_accounts')
    # ### end Alembic commands ###
