down:
	@docker compose -f dev-docker-compose.yml down

up:
	@docker compose -f dev-docker-compose.yml up

up_d:
	@docker compose -f dev-docker-compose.yml up -d

build:
	@docker compose -f dev-docker-compose.yml build

user_api_sh:
	@docker compose -f dev-docker-compose.yml exec user_api bash
