/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddBankDTO
 */
export interface AddBankDTO {
    /**
     * 
     * @type {string}
     * @memberof AddBankDTO
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AddBankDTO
     */
    apiUrl: string;
    /**
     * 
     * @type {string}
     * @memberof AddBankDTO
     */
    clientId: string;
    /**
     * 
     * @type {string}
     * @memberof AddBankDTO
     */
    clientSecret: string;
}

/**
 * Check if a given object implements the AddBankDTO interface.
 */
export function instanceOfAddBankDTO(value: object): value is AddBankDTO {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('apiUrl' in value) || value['apiUrl'] === undefined) return false;
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    if (!('clientSecret' in value) || value['clientSecret'] === undefined) return false;
    return true;
}

export function AddBankDTOFromJSON(json: any): AddBankDTO {
    return AddBankDTOFromJSONTyped(json, false);
}

export function AddBankDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddBankDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'apiUrl': json['apiUrl'],
        'clientId': json['clientId'],
        'clientSecret': json['clientSecret'],
    };
}

export function AddBankDTOToJSON(json: any): AddBankDTO {
    return AddBankDTOToJSONTyped(json, false);
}

export function AddBankDTOToJSONTyped(value?: AddBankDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'apiUrl': value['apiUrl'],
        'clientId': value['clientId'],
        'clientSecret': value['clientSecret'],
    };
}

