/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BankSchema
 */
export interface BankSchema {
    /**
     * 
     * @type {number}
     * @memberof BankSchema
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof BankSchema
     */
    name: string;
}

/**
 * Check if a given object implements the BankSchema interface.
 */
export function instanceOfBankSchema(value: object): value is BankSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function BankSchemaFromJSON(json: any): BankSchema {
    return BankSchemaFromJSONTyped(json, false);
}

export function BankSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): BankSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function BankSchemaToJSON(json: any): BankSchema {
    return BankSchemaToJSONTyped(json, false);
}

export function BankSchemaToJSONTyped(value?: BankSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

