/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConsentDataDTO
 */
export interface ConsentDataDTO {
    /**
     * 
     * @type {string}
     * @memberof ConsentDataDTO
     */
    bankClientId: string;
    /**
     * 
     * @type {string}
     * @memberof ConsentDataDTO
     */
    consentId: string;
}

/**
 * Check if a given object implements the ConsentDataDTO interface.
 */
export function instanceOfConsentDataDTO(value: object): value is ConsentDataDTO {
    if (!('bankClientId' in value) || value['bankClientId'] === undefined) return false;
    if (!('consentId' in value) || value['consentId'] === undefined) return false;
    return true;
}

export function ConsentDataDTOFromJSON(json: any): ConsentDataDTO {
    return ConsentDataDTOFromJSONTyped(json, false);
}

export function ConsentDataDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsentDataDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'bankClientId': json['bank_client_id'],
        'consentId': json['consent_id'],
    };
}

export function ConsentDataDTOToJSON(json: any): ConsentDataDTO {
    return ConsentDataDTOToJSONTyped(json, false);
}

export function ConsentDataDTOToJSONTyped(value?: ConsentDataDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bank_client_id': value['bankClientId'],
        'consent_id': value['consentId'],
    };
}

