/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JwtTokensSchema
 */
export interface JwtTokensSchema {
    /**
     * 
     * @type {string}
     * @memberof JwtTokensSchema
     */
    accessToken: string;
    /**
     * 
     * @type {string}
     * @memberof JwtTokensSchema
     */
    refreshToken: string;
}

/**
 * Check if a given object implements the JwtTokensSchema interface.
 */
export function instanceOfJwtTokensSchema(value: object): value is JwtTokensSchema {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    return true;
}

export function JwtTokensSchemaFromJSON(json: any): JwtTokensSchema {
    return JwtTokensSchemaFromJSONTyped(json, false);
}

export function JwtTokensSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): JwtTokensSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['accessToken'],
        'refreshToken': json['refreshToken'],
    };
}

export function JwtTokensSchemaToJSON(json: any): JwtTokensSchema {
    return JwtTokensSchemaToJSONTyped(json, false);
}

export function JwtTokensSchemaToJSONTyped(value?: JwtTokensSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
    };
}

