/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JwtTokensDTO
 */
export interface JwtTokensDTO {
    /**
     * 
     * @type {string}
     * @memberof JwtTokensDTO
     */
    accessToken: string;
    /**
     * 
     * @type {string}
     * @memberof JwtTokensDTO
     */
    refreshToken: string;
}

/**
 * Check if a given object implements the JwtTokensDTO interface.
 */
export function instanceOfJwtTokensDTO(value: object): value is JwtTokensDTO {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    return true;
}

export function JwtTokensDTOFromJSON(json: any): JwtTokensDTO {
    return JwtTokensDTOFromJSONTyped(json, false);
}

export function JwtTokensDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): JwtTokensDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['accessToken'],
        'refreshToken': json['refreshToken'],
    };
}

export function JwtTokensDTOToJSON(json: any): JwtTokensDTO {
    return JwtTokensDTOToJSONTyped(json, false);
}

export function JwtTokensDTOToJSONTyped(value?: JwtTokensDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
    };
}

