/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Status } from './Status';
import {
    StatusFromJSON,
    StatusFromJSONTyped,
    StatusToJSON,
    StatusToJSONTyped,
} from './Status';

/**
 * 
 * @export
 * @interface OkResponseSchema
 */
export interface OkResponseSchema {
    /**
     * 
     * @type {Status}
     * @memberof OkResponseSchema
     */
    status?: Status;
}

/**
 * Check if a given object implements the OkResponseSchema interface.
 */
export function instanceOfOkResponseSchema(value: object): value is OkResponseSchema {
    return true;
}

export function OkResponseSchemaFromJSON(json: any): OkResponseSchema {
    return OkResponseSchemaFromJSONTyped(json, false);
}

export function OkResponseSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): OkResponseSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : StatusFromJSON(json['status']),
    };
}

export function OkResponseSchemaToJSON(json: any): OkResponseSchema {
    return OkResponseSchemaToJSONTyped(json, false);
}

export function OkResponseSchemaToJSONTyped(value?: OkResponseSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': StatusToJSON(value['status']),
    };
}

