/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductRecommendation
 */
export interface ProductRecommendation {
    /**
     * 
     * @type {string}
     * @memberof ProductRecommendation
     */
    productId: string;
    /**
     * 
     * @type {string}
     * @memberof ProductRecommendation
     */
    productType: string;
    /**
     * 
     * @type {string}
     * @memberof ProductRecommendation
     */
    productName: string;
    /**
     * 
     * @type {string}
     * @memberof ProductRecommendation
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof ProductRecommendation
     */
    interestRate?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProductRecommendation
     */
    minAmount?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProductRecommendation
     */
    maxAmount?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProductRecommendation
     */
    termMonths?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ProductRecommendation
     */
    bank: string;
    /**
     * 
     * @type {string}
     * @memberof ProductRecommendation
     */
    notes?: string | null;
}

/**
 * Check if a given object implements the ProductRecommendation interface.
 */
export function instanceOfProductRecommendation(value: object): value is ProductRecommendation {
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('productType' in value) || value['productType'] === undefined) return false;
    if (!('productName' in value) || value['productName'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('bank' in value) || value['bank'] === undefined) return false;
    return true;
}

export function ProductRecommendationFromJSON(json: any): ProductRecommendation {
    return ProductRecommendationFromJSONTyped(json, false);
}

export function ProductRecommendationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductRecommendation {
    if (json == null) {
        return json;
    }
    return {
        
        'productId': json['productId'],
        'productType': json['productType'],
        'productName': json['productName'],
        'description': json['description'],
        'interestRate': json['interestRate'] == null ? undefined : json['interestRate'],
        'minAmount': json['minAmount'] == null ? undefined : json['minAmount'],
        'maxAmount': json['maxAmount'] == null ? undefined : json['maxAmount'],
        'termMonths': json['termMonths'] == null ? undefined : json['termMonths'],
        'bank': json['bank'],
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function ProductRecommendationToJSON(json: any): ProductRecommendation {
    return ProductRecommendationToJSONTyped(json, false);
}

export function ProductRecommendationToJSONTyped(value?: ProductRecommendation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'productId': value['productId'],
        'productType': value['productType'],
        'productName': value['productName'],
        'description': value['description'],
        'interestRate': value['interestRate'],
        'minAmount': value['minAmount'],
        'maxAmount': value['maxAmount'],
        'termMonths': value['termMonths'],
        'bank': value['bank'],
        'notes': value['notes'],
    };
}

