/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefreshTokenDTO
 */
export interface RefreshTokenDTO {
    /**
     * 
     * @type {string}
     * @memberof RefreshTokenDTO
     */
    refreshToken: string;
}

/**
 * Check if a given object implements the RefreshTokenDTO interface.
 */
export function instanceOfRefreshTokenDTO(value: object): value is RefreshTokenDTO {
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    return true;
}

export function RefreshTokenDTOFromJSON(json: any): RefreshTokenDTO {
    return RefreshTokenDTOFromJSONTyped(json, false);
}

export function RefreshTokenDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefreshTokenDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'refreshToken': json['refreshToken'],
    };
}

export function RefreshTokenDTOToJSON(json: any): RefreshTokenDTO {
    return RefreshTokenDTOToJSONTyped(json, false);
}

export function RefreshTokenDTOToJSONTyped(value?: RefreshTokenDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'refreshToken': value['refreshToken'],
    };
}

