/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResetPasswordDTO
 */
export interface ResetPasswordDTO {
    /**
     * 
     * @type {string}
     * @memberof ResetPasswordDTO
     */
    email: string;
}

/**
 * Check if a given object implements the ResetPasswordDTO interface.
 */
export function instanceOfResetPasswordDTO(value: object): value is ResetPasswordDTO {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function ResetPasswordDTOFromJSON(json: any): ResetPasswordDTO {
    return ResetPasswordDTOFromJSONTyped(json, false);
}

export function ResetPasswordDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetPasswordDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function ResetPasswordDTOToJSON(json: any): ResetPasswordDTO {
    return ResetPasswordDTOToJSONTyped(json, false);
}

export function ResetPasswordDTOToJSONTyped(value?: ResetPasswordDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

