/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetPasswordDTO
 */
export interface SetPasswordDTO {
    /**
     * 
     * @type {string}
     * @memberof SetPasswordDTO
     */
    password: string;
}

/**
 * Check if a given object implements the SetPasswordDTO interface.
 */
export function instanceOfSetPasswordDTO(value: object): value is SetPasswordDTO {
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function SetPasswordDTOFromJSON(json: any): SetPasswordDTO {
    return SetPasswordDTOFromJSONTyped(json, false);
}

export function SetPasswordDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetPasswordDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'password': json['password'],
    };
}

export function SetPasswordDTOToJSON(json: any): SetPasswordDTO {
    return SetPasswordDTOToJSONTyped(json, false);
}

export function SetPasswordDTOToJSONTyped(value?: SetPasswordDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'password': value['password'],
    };
}

