/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserTransactionsSchema
 */
export interface UserTransactionsSchema {
    /**
     * 
     * @type {number}
     * @memberof UserTransactionsSchema
     */
    userId: number;
    /**
     * 
     * @type {string}
     * @memberof UserTransactionsSchema
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof UserTransactionsSchema
     */
    currency: string;
    /**
     * 
     * @type {number}
     * @memberof UserTransactionsSchema
     */
    amount: number;
    /**
     * 
     * @type {Date}
     * @memberof UserTransactionsSchema
     */
    bookingDt: Date;
    /**
     * 
     * @type {Date}
     * @memberof UserTransactionsSchema
     */
    valueDt: Date;
    /**
     * 
     * @type {string}
     * @memberof UserTransactionsSchema
     */
    transactionInfo: string;
}

/**
 * Check if a given object implements the UserTransactionsSchema interface.
 */
export function instanceOfUserTransactionsSchema(value: object): value is UserTransactionsSchema {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('bookingDt' in value) || value['bookingDt'] === undefined) return false;
    if (!('valueDt' in value) || value['valueDt'] === undefined) return false;
    if (!('transactionInfo' in value) || value['transactionInfo'] === undefined) return false;
    return true;
}

export function UserTransactionsSchemaFromJSON(json: any): UserTransactionsSchema {
    return UserTransactionsSchemaFromJSONTyped(json, false);
}

export function UserTransactionsSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserTransactionsSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'status': json['status'],
        'currency': json['currency'],
        'amount': json['amount'],
        'bookingDt': (new Date(json['bookingDt'])),
        'valueDt': (new Date(json['valueDt'])),
        'transactionInfo': json['transactionInfo'],
    };
}

export function UserTransactionsSchemaToJSON(json: any): UserTransactionsSchema {
    return UserTransactionsSchemaToJSONTyped(json, false);
}

export function UserTransactionsSchemaToJSONTyped(value?: UserTransactionsSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'status': value['status'],
        'currency': value['currency'],
        'amount': value['amount'],
        'bookingDt': value['bookingDt'].toISOString(),
        'valueDt': value['valueDt'].toISOString(),
        'transactionInfo': value['transactionInfo'],
    };
}

