"""initial with usertable

Revision ID: 087964d90237
Revises: 
Create Date: 2025-10-31 15:25:41.094696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '087964d90237'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True, default=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True, default=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=True, default=False),
    sa.Column('is_staff', sa.Boolean(), nullable=True, default=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('username', sa.Text(), nullable=True, server_default=sa.text('gen_random_uuid()')),
    sa.Column('first_name', sa.Text(), nullable=True, default=None),
    sa.Column('last_name', sa.Text(), nullable=True, default=None),
    sa.Column('language', sa.String(length=3), nullable=True, default='ru'),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=True, default=None),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_user')
    # ### end Alembic commands ###
